apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-1
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - www.dreggystore.com
    secretName: letsencrypt-staging
  rules:
  - host: www.dreggystore.com
    http:
      paths:
      - path: /web
        pathType: Prefix
        backend:
          service:
            name: websvc
            port:
              number: 80
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: appsvc
            port:
              number: 80
