apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-1
  namespace: frontend
spec:
  ingressClassName: traefik
  rules:
    - host: www.dreggystore.com
      http:
        paths:
          - path: /web
            pathType: Exact
            backend:
              service:
                name:  websvc
                port:
                  number: 80
          - path: /app
            pathType: Exact
            backend:
              service:
                name:  appsvc
                port:
                  number: 80
