apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-ingress
  namespace: app

spec:
  rules:
    - host: www.dreggystore.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  web-svc
                port:
                  number: 80
          - path: /app
            pathType: Prefix
            backend:
              service:
                name:  web-svc
                port:
                  number: 80
